name: Tests

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check if the repository is private
        run: |
          if ${{ github.event.repository.private }}; then
            echo "Repository is private, skipping tests."
            exit 0
          fi
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # укажите нужную версию Node.js (18, 20, 22)
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run:
